### PR TITLE
feat(cache): compress contentful fallback cache

### PR DESCRIPTION
**Pull request by danieloraca**
Option to enable/disable compression on cache and fallback cache.

### CODE REVIEW

**Comment by gnanderson** [comment]
ping @shieldo would you have a look please if you have time this week?

**Comment by gsdevme** [comment]
@gnanderson @danieloraca it appears to be failing though?

**Comment by shieldo** [comment]
Hi all. Apologies for only getting to this now.

I'm not sure why this is being done this way - besides hard-coding in the options for using this compression, the cache being injected is already using PSR-6 as an interface - can't a userland implementation that does the compression be injected in instead? This would be far cleaner/ easier to test, and wouldn't involve changing this library that would be better agnostic of implementation details of caches.

We should really have discussions before work is done on changes like this. There are no unit tests, and no plan for how to support existing caches that haven't received this compression, thus (temporarily) breaking any application using this code (because `\LogicException's are unexpectedly thrown), including those run by Markup (though other people do use this library too). It's also making assumptions about what is being saved in the cache, and about levels of compression that would be attained. (Has any kind of audit been undertaken to see what are the individual cache sizes here and to what extent these would benefit from compression? Certainly for relatively small strings compression will more likely _increase_ size. `gzdeflate()` / `gzinflate()` are better PHP functions for this as they exclude unnecessary metadata.)

While I'm not arguing against the use of compression per se - a user of the library may inject whichever cache they like after all, and its efficacy is a different subject - I am sorry but I can't merge a PR like this - it's too dangerous both for its intended use and for other users of this library. I'd advise writing a simple adapter in userland code that can decorate another cache implementation with compression, that can then be well tested with cutover scenarios considered.

**Comment by gsdevme** [comment]
Other points aside Is the overhead of compression functions not about 18 bytes? in terms of the headers, based on https://stackoverflow.com/questions/621976/which-compression-method-to-use-in-php

Doesn't seem important, gzcompress uses ZLIB and has a built-in checksum which sounds useful.

**Comment by shieldo** [comment]
The point was really that there's no evidence provided here for why compression is needed and would make a substantive difference. Especially on a public library like this, we should be working to a higher bar. Which exact PHP function to use, however, is less of a concern than the other points.

**Pull request closed without merging**
